### ISSUE TITLE
very slow and issues in nvidia jetson

### ISSUE THREAD

**Issue by Links17** [second-state/WasmEdge-WASINN-examples#112]
When I use nvidia Jetson AGX orin, cuda 8.7 to run LLaVA, he is very slow, it looks like it's not using the GPU but the CPU!
<img width="407" alt="image" src="https://github.com/second-state/WasmEdge-WASINN-examples/assets/61582001/83ed4231-7a72-4d92-b64c-d53787ee7407">
it'll take about 20s.
```bash
wasmedge --dir .:.   --env mmproj=mmproj-model-f16.gguf   --env image=monalisa.jpg   --env n-gpu-layers=35   --env threads=40   --nn-preload default:GGML:AUTO:ggml-model-q5_k.gguf   wasmedge-ggml-llava.wasm default
```

**Comment by hydai** [comment]
Hi @Links17 
You should use `n_gpu_layers` instead.

See: https://github.com/second-state/WasmEdge-WASINN-examples/blob/master/wasmedge-ggml/llava/src/main.rs#L50

**Comment by Links17** [comment]
Thanks a lot for the answer, it's my problem.
