### ISSUE TITLE
qwen1_5-14b-chat-q5_k_m.gguf is not working 

### ISSUE THREAD

**Issue by njalan** [second-state/WasmEdge-WASINN-examples#116]
In my testing qwen1_5-14b-chat-q5_k_m.gguf is working with llama.cpp but not work with wasmedge & llama-chat.wasm.

Here is my command:
wasmedge --dir .:.   --nn-preload default:GGML:CPU:qwen1_5-14b-chat-q5_k_m.gguf  llama-chat.wasm -c 2048 -n 512 -g 0
there is nothing output

<img width="658" alt="image" src="https://github.com/second-state/WasmEdge-WASINN-examples/assets/8622340/c7148599-67b0-41e4-b4a0-878883091a88">

**Comment by njalan** [comment]
@hydai Can you please help to look at this?

**Comment by dm4** [comment]
Qwen is using the ChatML template format for prompts; you need to add the `-p chatml` argument to your command. It should work out-of-the-box using the latest release of the GGML plugin.

<img width="982" alt="qwen" src="https://github.com/second-state/WasmEdge-WASINN-examples/assets/274041/90eec3e1-c5a9-4705-b5d6-e3847b71a3ae">

Additionally, `llama-chat.wasm` originates from [LlamaEdge/chat](https://github.com/LlamaEdge/LlamaEdge/tree/main/chat); perhaps you should consider raising an issue [here](https://github.com/LlamaEdge/LlamaEdge/issues) as a first step next time.

**Comment by njalan** [comment]
@dm4 Thanks for your help
