### ISSUE TITLE
terminate called after throwing an instance of 'torch::jit::ErrorReport' terminate called recursively Aborted (core dumped)

### ISSUE THREAD

**Issue by lebron8dong** [second-state/WasmEdge-WASINN-examples#128]
python 3.8.19
pytorch 1.8.2

1. run gen_mobilenet_model.py to generate mobilenet.pt

2. wasmedge --dir .:. wasmedge-wasinn-example-resnet50-image.wasm mobilenet1.pt input.jpg
error : terminate called after throwing an instance of 'torch::jit::ErrorReport' terminate called recursively Aborted (core dumped)

3. when I use the pre-generate one at mobilenet.pt , it successfully execute.

**Comment by hydai** [comment]
I got confused by your command. Are you trying to run `resnet50` with `mobilenet`?

**Comment by lebron8dong** [comment]
Sorry, I forgot to change the file name. I matched the python version and model to PyTorch 1.8.2 LTS and there were no errors.

**Comment by hydai** [comment]
Is this issue fixed? If you want to use another version of Python/PyTorch, you may need to update the related deps files.
