### ISSUE TITLE
[pytorch] The malformed wasm file

### ISSUE THREAD

**Issue by apepkuss** [second-state/WasmEdge-WASINN-examples#13]
The [wasmedge-wasinn-example-mobilenet-image.wasm](https://github.com/second-state/WasmEdge-WASINN-examples/blob/master/pytorch-mobilenet-image/wasmedge-wasinn-example-mobilenet-image.wasm) seems malformed. I failed to load it via Rust SDK, and also WebAssembly Toolkit failed to parse it. Could you please check it again? By the way, the generated wasm file from the `rust` directory works correctly. Thanks!

Updated 2022/10/17:

I tried to run the `pytorch-mobilenet-image` example with the wasm file, the model file and the input image provided in the example directory. The error message was shown as the snapshot below. According to the error message, the `image_to_tensor` function failed to work.

![image](https://user-images.githubusercontent.com/4726889/196186082-f8b29b43-d3ef-4f2b-aa69-42906e570e5b.png)

**Comment by arnabnandikgp** [comment]
Hi,
I think you do not have the input.jpg in your current directory, that's why its not able to read it and convert it to tensors.
