### ISSUE TITLE
Question: yolo use ggml as the backend,need help...

### ISSUE THREAD

**Issue by jokemanfire** [second-state/WasmEdge-WASINN-examples#140]
Now  I see it looks like didn't support yolo* series model, Is there some plans to add yolo? I want to use yolo in some embedded system and use ggml as the backend.  >_<

**Comment by hydai** [comment]
YOLO series models are not supported by llama.cpp. However, llama.cpp and WasmEdge are open source projects. Welcome to submit a PR to fix it.

**Comment by jokemanfire** [comment]
> YOLO series models are not supported by llama.cpp. However, llama.cpp and WasmEdge are open source projects. Welcome to submit a PR to fix it.

it looks like I must learn about llama.cpp , and have to try. Thanks.  Q_Q
