### ISSUE TITLE
Does docker support WASI-NN with PyTorch Backend?

### ISSUE THREAD

**Issue by warpmatrix** [second-state/WasmEdge-WASINN-examples#20]
I notice that the wasi-nn only run at host as described in `pytorch-mobilenet-image/README.md` without any description for docker. I wonder whether docker supports for wasi-nn with Pytorch backend. Do I need to install "WASI-NN plugin with PyTorch backend" by `RUN` command in `Dockerfile`, or there will be WasmEdge DockerSlim for wasi-nn with Pytorch backend?

**Comment by juntao** [comment]
Docker Desktop and runwasi will support running WASI NN plugins in the next version (hopefully in a month). 

Once it is available, you will need to package the Wasm file, PyTorch C library, and the model file in a SCRATCH container. The total image size is around 
 5MB + model size.

**Comment by juntao** [comment]
It is in fact possible to have the PyTorch library installed on the host not in the image. But we feel that people probably would rather NOT installing these on the host.

The way it works is that the runwasi will unpack the files in the image, setup the path, and then hand the Wasm file to WasmEdge. So, I believe the GPU version of PyTorch should work just fine.

**Comment by warpmatrix** [comment]
That sounds good to me! Thanks again for your patient reply and the great work of your team. And I'll close this issue.
