### ISSUE TITLE
Update the examples to 0.13.1 and above

### ISSUE THREAD

**Issue by juntao** [second-state/WasmEdge-WASINN-examples#21]
Since we now have a new NN plugin system, let's update the examples:

1. Use the official release files to install WasmEdge and plugins in the GitHub Actions CI. Do not build from the source.
2. Create CI actions for TF, TFLite, PyTorch, OpenVINO examples. We could have 4 separate GitHub Actions `yaml` files -- one for each example. 
3. Update the `wasi-nn` crate in all examples to the latest (no more `unsafe`)
4. Update the README for each example to be consistent with the successful CI.
5. Note in the PyTorch and TFLite READMEs how to run on GPUs.

**Comment by hydai** [comment]
Do we still need this issue?

**Comment by juntao** [comment]
I will close this. We will need a different set of docs.
