### ISSUE TITLE
Update the OpenVINO document after WasmEdge 0.13.2 released

### ISSUE THREAD

**Issue by hydai** [second-state/WasmEdge-WASINN-examples#25]
# Overview
In the 0.13.2 release, OpenVINO bumped its version from 2021 to 2023, which changed the installation guide. See https://github.com/WasmEdge/docs/issues/136

We should refer to the corresponding website instead of maintaining a standalone installation guide in this repo.

# Details

1. Modify the README to use the OpenVINO document from the WasmEdge/docs repo/website
2. Remove everything related to OpenVINO 2021.

**Comment by Mash707** [comment]
Hii @hydai I will be working on this issue.
