### ISSUE TITLE
CI jobs for ggml llama run failed

### ISSUE THREAD

**Issue by dm4** [second-state/WasmEdge-WASINN-examples#29]
For CI job: [WasmEdge-WASINN-examples CI Job](https://github.com/second-state/WasmEdge-WASINN-examples/actions/runs/6088393552/job/16527821921)

The failed output is `/home/runner/work/_temp/f00accda-a30f-4196-bdc0-a4217b2f5991.sh: line 5:  4181 Killed`. It appears to have been terminated due to an Out-of-Memory (OOM) issue.

I also measured the memory usage of the same task on my local machine. The results are as follows:

```
cat /proc/463407/status | grep -E '^(VmHWM|VmPeak)'
VmPeak: 31614884 kB
VmHWM: 18600392 kB
```

The maximum total memory usage is approximately 32 GB, and the peak resident set size is around 19 GB.

According to [GitHub's documentation on hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners), GitHub runners have only 7 GB of RAM. Therefore, I believe that the OOM issue is the reason our CI job failed.

**Comment by juntao** [comment]
Oh! Perhaps we should try a 3B or even smaller ggml model in the CI? 😅

**Comment by juntao** [comment]
And this one works ... 

https://github.com/juntao/llama-api-demo/blob/main/.github/workflows/api-server.yml

It is 7B model on GitHub Actions
