### ISSUE TITLE
free(): invalid pointer Aborted (core dumped) on arm64 arch linux.

### ISSUE THREAD

**Issue by shahizat** [second-state/WasmEdge-WASINN-examples#48]
Hello, 

Could you please help me with the issue above when I run it using the following command on the NVIDIA Jetson AGX Orin Developer Kit? I used pre built version of wasmedge-ggml-llama-interactive.wasm and built from source as well. 

`wasmedge --dir .:. \
  --nn-preload default:GGML:CPU:llama-2-7b-chat.Q5_K_M.gguf \
  wasmedge-ggml-llama-interactive.wasm default`

**Comment by hydai** [comment]
Hi @shahizat 
This is tracking in this upstream issue: https://github.com/WasmEdge/WasmEdge/issues/2951
The current pre-built WasmEdge ggml plugin is incompatible with the Ubuntu 20.04 aarch64 platform. This is related to the c++11abi issue. We are going to have new release assets on such a platform soon.

**Comment by shahizat** [comment]
Hi @hydai, wow, thanks for your prompt reply, I've already attempted to run it on the AMD64 machine with a 32-core CPU, and the speed of generation is truly impressive. I wonder.. is it possible to run it using a GPU as well?

**Comment by hydai** [comment]
@shahizat 
The answer is YES!!! I am working on it. Said enabling the cuBLAS to accelerate with CUDA and GPU.
Here is the working PR: https://github.com/WasmEdge/WasmEdge/pull/2952

The following output is on my Jetson Orin machine. (CUDA11 + cuBLAS)

```
llm_load_tensors: ggml ctx size =    0.09 MB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: mem required  =   86.03 MB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 35/35 layers to GPU
llm_load_tensors: VRAM used: 4474.93 MB
...................................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: offloading v cache to GPU
llama_kv_cache_init: offloading k cache to GPU
llama_kv_cache_init: VRAM kv self = 256.00 MB
llama_new_context_with_model: kv self size  =  256.00 MB
llama_new_context_with_model: compute buffer total size = 76.38 MB
llama_new_context_with_model: VRAM scratch buffer: 70.50 MB
llama_new_context_with_model: total VRAM used: 4801.43 MB (model: 4474.93 MB, context: 326.50 MB)
[2023-10-11 09:26:42.465] [info] [WASI-NN] GGML backend: llama_system_info: AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 |

llama_print_timings:        load time =  2704.58 ms
llama_print_timings:      sample time =     7.04 ms /    63 runs   (    0.11 ms per token,  8950.13 tokens per second)
llama_print_timings: prompt eval time =   362.00 ms /    13 tokens (   27.85 ms per token,    35.91 tokens per second)
llama_print_timings:        eval time =  3459.96 ms /    62 runs   (   55.81 ms per token,    17.92 tokens per second)
llama_print_timings:       total time =  6173.45 ms
```

**Comment by VestigeJ** [comment]
Hoping to build the .wasm this afternoon, i’m on the more modest but usefully small Jetson Nano 4GB. Will report back later

**Comment by VestigeJ** [comment]
Tangentially related if you want to not overburden the devices but get some solid inference outputs check out the phi 1.5 models. The only ones i’ve found so far in GGUF format https://huggingface.co/lmz/candle-quantized-phi/tree/main

**Comment by juntao** [comment]
The orca mini model used in our GitHub Actions CI is also pretty good. It should fit into 4GB of RAM. 

https://github.com/second-state/WasmEdge-WASINN-examples/blob/master/.github/workflows/llama.yml

**Comment by hydai** [comment]
Hi @shahizat 
This issue is fixed in the 0.13.5 release. Please try again on the Jetson Orin. Thanks!

Hi @VestigeJ 

And we also updated the way to configure the GPU LAYERS: https://github.com/second-state/WasmEdge-WASINN-examples/tree/master/wasmedge-ggml-llama-interactive#parameters

So, you can use a small number of layers to make the llama2 7b model load on your device.


If you encounter any new issues, please feel free to re-open this.

**Comment by shahizat** [comment]
Hi @hydai  and @juntao , thank you for your update. Indeed, it is working well. Just FYI, this model (https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/tree/main) is much faster and provides decent answers.

**Comment by hydai** [comment]
Hi @shahizat 
Awesome! Happy to hear that. And thanks for the update with us :-).
