### ISSUE TITLE
Error Running WasmEdge with llama2 Model: GGML_ASSERT Failure

### ISSUE THREAD

**Issue by xISSAx** [second-state/WasmEdge-WASINN-examples#66]
## System:
MacBook: Apple M1 8 GB MacOS Sonoma v 14.1.1
wasmedge version: 0.13.5

## Issue Description:
I am encountering an error when attempting to run a llama2 model using WasmEdge. The command and error message are as follows:

### Command:
```
wasmedge --dir .:. --nn-preload default:GGML:AUTO:llama-2-7b-chat.Q2_K.gguf
```

### Error:
```
GGML_ASSERT: /Users/hydai/workspace/WasmEdge/plugins/wasi_nn/thirdparty/ggml/ggml-metal.m:1459: false
zsh: abort      wasmedge --dir .:. --nn-preload default:GGML:AUTO:llama-2-7b-chat.Q2_K.gguf
```

## Steps to Reproduce:

1. Installed WasmEdge with GGML plugin using the provided installation script.
2. Downloaded llama-chat.wasm and the llama2 model in GGUF format.
3. Ran the above command in the directory containing these files.

## Expected Behavior:
Expected to run the model without errors for a chat interface.

## Actual Behavior:
Received the GGML_ASSERT error and the process aborted.

## More Info:
```
(base) my_user ~ % wasmedge --dir .:. --nn-preload default:GGML:AUTO:llama-2-7b-chat.Q2_K.gguf llama-chat.wasm

 [INFO] Model alias: default
 [INFO] Prompt context size: 4096
 [INFO] Number of tokens to predict: 1024
 [INFO] Number of layers to run on the GPU: 100
 [INFO] Batch size for prompt processing: 4096
 [INFO] Use default system prompt
 [INFO] Prompt template: Llama2Chat
 [INFO] Stream stdout: false
 [INFO] Log prompts: false
 [INFO] Log statistics: false
 [INFO] Log all information: false
----------------------------------------------------

[USER]: 
Hey there!
GGML_ASSERT: /Users/hydai/workspace/WasmEdge/plugins/wasi_nn/thirdparty/ggml/ggml-metal.m:1459: false
zsh: abort      wasmedge --dir .:. --nn-preload default:GGML:AUTO:llama-2-7b-chat.Q2_K.gguf 
```

At first I thought it was memory overflow due to Q_5_K_M, so I downloaded Q2_K, but no luck.
Also, I've already tried re-installing it multiple times. Yes, I restarted too! :)
Any insights or suggestions to resolve this issue would be greatly appreciated.

**Comment by juntao** [comment]
Hmm, where is the Wasm file (eg llama-chat.wasm or llama-simple.wasm) in your command line?

**Comment by juntao** [comment]
This is very strange. Can I ask you to try a even smaller model?

BabyLlama: https://huggingface.co/second-state/TinyLlama-1.1B-Chat-v0.3-GGUF/resolve/main/tinyllama-1.1b-chat-v0.3.Q5_K_M.gguf

Thanks!

**Comment by xISSAx** [comment]
Thanks @juntao 

Happy to report, **using the smaller BabyLlama model worked well.**

I noticed a significant advantage in terms of processing tokens quickly with WasmEdge, particularly in the sample time and rate. Here's a brief comparison of the performance between llama cpp and WasmEdge using this smaller model:

## Llama CPP:
```
Load Time: 1295.95 ms
Sample Time: 0.46 ms/token (2164.56 tokens/sec)
Prompt Eval Time: 23.85 ms/token (41.92 tokens/sec)
Evaluation Time: 19.46 ms/token
Total Time: 20081.81 ms
```

## WasmEdge:
```
Load Time: 4285.18 ms
Sample Time: 0.19 ms/token (5238.30 tokens/sec) - big W! 🔥
Prompt Eval Time: 36.38 ms/token (27.49 tokens/sec)
Evaluation Time: 19.93 ms/token
Total Time: 16429.21 ms - big W! 🔥
````

Finally, one more little thing, I had hit that snag again during extended/longer chat sessions. I bet it's my smol ram again, but I hope there is a way around it.

### With these in mind, I have a couple of questions:

1. **Running on Larger Models:** Is there a way to efficiently run WasmEdge on larger models while maintaining or improving performance metrics, especially in areas where it currently has an advantage?
2. **Error in Extended Use:** Any insights on why the error might reappear in longer chat sessions and how it might be resolved?

**Comment by juntao** [comment]
Cool! Yeah, 8GB is small for these models (they are called LARGE language models ;)). I can run the 7B model quite reliably on my 16GB M2, but the 13B model often runs out of memory.

The error you saw after a few turn if the conversation probably indicates that you are running out of the memory. The memory use increases as the conversation goes on since for every question, the LLM must process the entire conversation history. It reaches a plateau when the context length (4096 tokens for llama2) is reached.

To use larger models, I would suggest more memory ... You could get a lot if cheap RAM on a CPU-only device or VM. It will be slow but it would not crash.

**Comment by gblazex** [comment]
I also had this problem on 8GB Macbook. LM Studio runs the same 7B model fine (13 tokens/sec).

WasmEdge however gives the same error as OP:
GGML_ASSERT: /Users/hydai/workspace/WasmEdge/plugins/wasi_nn/thirdparty/ggml/ggml-metal.m:1459: false

I believe this could be fixed.

**Comment by hydai** [comment]
Hi @xISSAx and @gblazex 

Since I don't have an 8GB model, I can reproduce this issue on an M2 8GB MacBook in an Apple Store. Unfortunately, I don't have too much time to debug it in the store.

Could you please try the following commands instead to see if the problem still happens? If still no luck, could you please share the output with us?

```
wasmedge --dir .:. --nn-preload default:GGML:AUTO:llama-2-7b-chat.Q2_K.gguf llama-chat.wasm --ctx-size 512 --batch-size 512 --log-all
```

The default value of llama.cpp is 512. I am just wondering if the 4096 is too large to run on the 8GB memory devices.

**Comment by hydai** [comment]
Hi @xISSAx and @gblazex 
We updated the `run-llm.sh` to reduce the default ctx-size and batch-size from 4096 to 512. Now, it should work on 8GB devices. Ref: https://github.com/second-state/llama-utils/pull/52

Please feel free to re-open this issue, if you still encounter the same problem after using the latest version. Thanks.

**Comment by gblazex** [comment]
great work, will try! @hydai
