### ISSUE TITLE
Failing to install WasmEdge through Curl "302 Moved Temporarily"

### ISSUE THREAD

**Issue by niranjanakella** [second-state/WasmEdge-WASINN-examples#68]
Tried to run the following on my mac. 
```
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugin wasi_nn-ggml
```
But it is giving me 
```
bash: line 1: html: No such file or directory
bash: line 2: syntax error near unexpected token `<'
'ash: line 2: `<head><title>302 Moved Temporarily</title></head>
```
@hydai kindly help

**Comment by niranjanakella** [comment]
UPDATE: Found work around

Clone the WasmEdge repo
```
git clone https://github.com/WasmEdge/WasmEdge.git
```
Then navigate to utils/install.py and then open it in vim editor and remove the ssl certificate validation by adding the following line at the top of script
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```
Then run the script with `python3 install.py --plugin wasi_nn-ggml`

This should temporarily solve the issue

**Comment by hydai** [comment]
![CleanShot 2023-11-18 at 01 24 47](https://github.com/second-state/WasmEdge-WASINN-examples/assets/2776756/41532289-78c9-4843-9992-fd0d0494d5d2)

I am not sure what the issue is. I cannot reproduce this.

**Comment by niranjanakella** [comment]
@hydai  I tried it again and I received the following error. I have tried to uninstall and reinstall curl through brew too and it works well for other curl commands. 
<img width="992" alt="Screenshot 2023-11-19 at 11 56 12 AM" src="https://github.com/second-state/WasmEdge-WASINN-examples/assets/45909563/064b019b-57ab-466e-964a-06968a1dab2a">

**Comment by niranjanakella** [comment]
I have also tried cloning the repo first and running the install.sh command locally and received an error that the install.py isn't rechable. 

<img width="724" alt="Screenshot 2023-11-19 at 11 59 55 AM" src="https://github.com/second-state/WasmEdge-WASINN-examples/assets/45909563/04d76cc1-fa99-41a2-82eb-6e5501e91614">

**Comment by niranjanakella** [comment]
Issue related to SSL Certificates

Looks like this is an issue of SSL certificate. Since I am using a corporate device it's tethered to proxy. For any such corporate users, try using the first solution that I have provided that installs WasmEdge from source repo using install.py script. 

Thank you for the response @hydai
