### ISSUE TITLE
bug: Failed to run example in "wasmedge-ggml-llama-interative" with error "thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BackendError(ContextFull)'"

### ISSUE THREAD

**Issue by MaTwickenham** [second-state/WasmEdge-WASINN-examples#86]
Command `wasmedge-ggml-llama-interactive % wasmedge --dir .:. --nn-preload default:GGML:AUTO:llama-2-7b-chat.Q5_K_M.gguf wasmedge-ggml-llama-interactive.wasm default` in folder `wasmedge-ggml-llama-interative` raised 

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BackendError(ContextFull)', src/main.rs:215:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2024-01-22 20:37:42.436] [error] execution failed: unreachable, Code: 0x89
[2024-01-22 20:37:42.436] [error]     In instruction: unreachable (0x00) , Bytecode offset: 0x0001980e
[2024-01-22 20:37:42.436] [error]     When executing function name: "_start"

My device is Apple M1 16G. Could this be related to insufficient memory?
<img width="748" alt="image" src="https://github.com/second-state/WasmEdge-WASINN-examples/assets/87300449/f88cb579-0e37-467f-ba8a-6a21691965a7">

**Comment by hydai** [comment]
Hi @MaTwickenham 
This is related to https://github.com/second-state/WasmEdge-WASINN-examples/pull/85
Please add `-stream-stdout=false` as a workaround to avoid it.

We are going to merge the `dev` branch tomorrow.

**Comment by MaTwickenham** [comment]
> Hi @MaTwickenham This is related to #85 Please add `-stream-stdout=false` as a workaround to avoid it.
> 
> We are going to merge the `dev` branch tomorrow.

Thanks! It works.
